
-- Создание тестового пользователя с правильным хешем пароля
-- Пароль: test123 (хеш сгенерирован с bcrypt, 10 раундов)

INSERT INTO users (
  id,
  email,
  login,
  full_name,
  password_hash,
  phone,
  country,
  country_name,
  is_verified,
  is_active,
  email_verified,
  balance,
  total_invested,
  total_earned,
  referral_code,
  role_id,
  status,
  created_at,
  updated_at,
  last_login
) VALUES (
  gen_random_uuid(),
  'test@test.com',
  'testuser',
  'Test User',
  '$2a$10$jQ0zKnWc8N8Q5Q4Q4Q4Q4u4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Qu',
  '+1234567890',
  'RU',
  'Россия',
  true,
  true,
  true,
  1000.00,
  0.00,
  0.00,
  'TEST001',
  2,
  'active',
  NOW(),
  NOW(),
  NULL
) ON CONFLICT (email) DO UPDATE SET
  login = EXCLUDED.login,
  password_hash = EXCLUDED.password_hash,
  updated_at = NOW();

-- Создаем админа для тестирования
INSERT INTO users (
  id,
  email,
  login,
  full_name,
  password_hash,
  phone,
  country,
  country_name,
  is_verified,
  is_active,
  email_verified,
  balance,
  total_invested,
  total_earned,
  referral_code,
  role_id,
  status,
  created_at,
  updated_at,
  last_login
) VALUES (
  gen_random_uuid(),
  'admin@test.com',
  'admin',
  'Admin User',
  '$2a$10$jQ0zKnWc8N8Q5Q4Q4Q4Q4u4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Q4Qu',
  '+1234567891',
  'RU',
  'Россия',
  true,
  true,
  true,
  10000.00,
  0.00,
  0.00,
  'ADMIN001',
  1,
  'active',
  NOW(),
  NOW(),
  NULL
) ON CONFLICT (email) DO UPDATE SET
  login = EXCLUDED.login,
  password_hash = EXCLUDED.password_hash,
  role_id = EXCLUDED.role_id,
  updated_at = NOW();
